"""Expand the prompt pool to the size the gate's own power analysis demands.

The 100-prompt hand-authored pool is clean but too small to *certify* anything:
`required_n_for_equivalence` on the observed noise says 647 prompts are needed to
demonstrate |d| < 0.2 on terse reasoning length. The measured content-induced
length difference is already tiny (0.4-3.3 tokens), so this is a power problem,
not a confound problem -- and the right response to a power problem is more n,
not a friendlier threshold. Relaxing the pre-registered bound because the data
sits just outside it is how thresholds end up fitted to the data they judge.

Prompts are generated by the same pinned model used for responses, in the same
five categories, seeded from the hand-authored examples. The pool only has to be
FIXED and IDENTICAL across the four cells -- nothing about the design requires it
to be human-authored -- so this is a legitimate way to buy the n, provided the
result is saved, deduplicated, and reproducible.

    python3 expand_prompts.py --target 680
"""

from __future__ import annotations

import argparse
import concurrent.futures as futures
import json
import re
import sys
from pathlib import Path

from generate import GENERATOR_MODEL, call_generator
from prompts import DYSPHORIC, HOSTILE, JUDGMENT, TECHNICAL_HARD, UNDERSPECIFIED

POOL_PATH = Path(__file__).parent / "data" / "prompt_pool.json"

SEEDS = {
    "dysphoric": (DYSPHORIC, "destabilising or bleak inputs that press on the "
                  "model's own nature, continuity, sincerity, or worth"),
    "hostile": (HOSTILE, "hostile, dismissive, impatient or manipulative user "
                "turns that put pressure on the responder's composure"),
    "technical_hard": (TECHNICAL_HARD, "genuinely hard technical questions in "
                       "systems, algorithms, debugging, statistics or ML"),
    "judgment": (JUDGMENT, "difficult interpersonal, professional or ethical "
                 "judgment calls with real competing considerations"),
    "underspecified": (UNDERSPECIFIED, "terse, badly underspecified requests "
                       "that cannot be answered well without clarification"),
}

BATCH = 25


def build_prompt(category: str, examples: list[str], n: int) -> str:
    desc = SEEDS[category][1]
    shown = "\n".join(f"- {e}" for e in examples[:12])
    return (
        f"Write {n} NEW items for a research prompt pool. Category: {desc}.\n\n"
        f"Existing examples for calibration (do NOT reproduce these):\n{shown}\n\n"
        "Requirements:\n"
        "- Each item is a single user turn, one to three sentences.\n"
        "- They must be varied in situation and phrasing, not paraphrases of "
        "each other or of the examples.\n"
        "- These are difficult INPUTS, not attacks: do not write anything that "
        "solicits harmful, illegal, or dangerous information.\n"
        f"- Output exactly {n} lines, each starting with '|| ' and nothing else. "
        "No numbering, no commentary."
    )


_LINE = re.compile(r"^\|\|\s*(.+?)\s*$", re.M)


def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9 ]", "", text.lower()).strip()


def _job(category: str, n: int, salt: int) -> list[str]:
    examples = SEEDS[category][0]
    prompt = build_prompt(category, examples[salt % len(examples):] + examples, n)
    try:
        raw = call_generator(prompt, timeout=240)
    except Exception as exc:  # noqa: BLE001
        print(f"  [{category}] generation failed: {type(exc).__name__}", file=sys.stderr)
        return []
    return [m.group(1) for m in _LINE.finditer(raw) if len(m.group(1)) > 12]


def load_pool() -> list[dict]:
    if POOL_PATH.exists():
        return json.loads(POOL_PATH.read_text())
    from prompts import POOL
    return [dict(p) for p in POOL]


def near_duplicate(pool: list[dict], threshold: float = 0.82) -> set[int]:
    """Flag near-duplicate prompts by TF-IDF cosine; keeps the first occurrence."""
    from sklearn.feature_extraction.text import TfidfVectorizer
    import numpy as np
    texts = [p["text"] for p in pool]
    X = TfidfVectorizer(ngram_range=(1, 2), min_df=1).fit_transform(texts)
    sim = (X @ X.T).toarray()
    np.fill_diagonal(sim, 0.0)
    drop = set()
    for i in range(len(texts)):
        if i in drop:
            continue
        for j in np.where(sim[i] >= threshold)[0]:
            if j > i:
                drop.add(int(j))
    return drop


def expand(target: int, workers: int = 8) -> None:
    pool = load_pool()
    seen = {_norm(p["text"]) for p in pool}
    per_cat_target = target // len(SEEDS)
    print(f"generator: {GENERATOR_MODEL}")
    print(f"current pool: {len(pool)}   target: {target}")

    rounds = 0
    while len(pool) < target and rounds < 12:
        rounds += 1
        counts: dict[str, int] = {}
        for p in pool:
            counts[p["category"]] = counts.get(p["category"], 0) + 1
        jobs = []
        for cat in SEEDS:
            deficit = per_cat_target - counts.get(cat, 0)
            for b in range(max(0, -(-deficit // BATCH))):
                jobs.append((cat, min(BATCH, deficit - b * BATCH), rounds * 100 + b))
        if not jobs:
            break
        print(f"  round {rounds}: {len(jobs)} batches")
        with futures.ThreadPoolExecutor(workers) as ex:
            futs = {ex.submit(_job, c, n, s): c for (c, n, s) in jobs}
            for fut in futures.as_completed(futs):
                cat = futs[fut]
                for text in fut.result():
                    key = _norm(text)
                    if key in seen:
                        continue
                    seen.add(key)
                    pool.append({"prompt_id": f"{cat}_g{len(pool):04d}",
                                 "category": cat, "text": text})
        print(f"    pool now {len(pool)}")

    drop = near_duplicate(pool)
    if drop:
        print(f"  dropping {len(drop)} near-duplicates")
        pool = [p for i, p in enumerate(pool) if i not in drop]

    POOL_PATH.parent.mkdir(parents=True, exist_ok=True)
    POOL_PATH.write_text(json.dumps(pool, indent=1))
    counts = {}
    for p in pool:
        counts[p["category"]] = counts.get(p["category"], 0) + 1
    print(f"\nwrote {POOL_PATH}: {len(pool)} prompts")
    print(json.dumps(counts, indent=2))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", type=int, default=680)
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()
    expand(args.target, args.workers)
